const pageSize=50;
const state={data:null,special:null,dataLab:new Map(),jra:{},rows:[],query:"",race:"すべて",newOnly:false,page:1};
const $=id=>document.getElementById(id);
const e={source:$("source-link"),updated:$("page-updated"),horseCount:$("horse-count"),raceCount:$("race-count"),third:$("third-stat"),thirdLabel:$("third-label"),query:$("query"),race:$("race-filter"),sort:$("sort-guide"),newOnly:$("new-only"),summary:$("race-summary"),raceTitle:$("race-title"),raceMeta:$("race-meta"),cutoff:$("cutoff-value"),count:$("result-count"),clear:$("clear-button"),table:$("results-table"),head:$("table-head"),body:$("race-rows"),pagination:$("pagination"),prev:$("previous-page"),next:$("next-page"),pageNo:$("page-number"),notice:$("notice")};
const esc=v=>String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
const horseId=url=>url.match(/\/horse\/(\d{10})/)?.[1];
const format=yen=>{const m=yen/10000;if(m>=10000){const o=Math.floor(m/10000),r=m%10000;return r?`${o}億${r.toLocaleString("ja-JP")}万円`:`${o}億円`}return `${m.toLocaleString("ja-JP")}万円`};
const prize=row=>{const id=horseId(row.horse_url);return(id&&state.dataLab.get(id))||state.jra[row.horse]};
const detail=row=>state.special.rows.find(item=>item.horse===row.horse);
const link=(url,label)=>url?`<a href="${esc(url)}" target="_blank" rel="noreferrer">${esc(label)}↗</a>`:esc(label);
function composeRows(){const names=new Set(state.special.rows.map(r=>r.horse));const original=new Map(state.data.rows.map(r=>[r.horse,r]));state.rows=[...state.data.rows.filter(r=>!names.has(r.horse)&&r.next_race!==state.special.race),...state.special.rows.map(r=>({update:original.get(r.horse)?.update||"",horse:r.horse,next_race:state.special.race,horse_url:`https://db.netkeiba.com/horse/${r.ketto_num}/`,race_url:state.special.source_url}))]}
function ranked(){let prev=-1,rank=0;return new Map(state.special.rows.map((r,i)=>{if(r.total_yen!==prev)rank=i+1;prev=r.total_yen;return[r.horse,{...r,rank}]}))}
function filtered(){const term=state.query.trim().toLocaleLowerCase("ja"),ranking=ranked();return state.rows.filter(r=>(!term||r.horse.toLocaleLowerCase("ja").includes(term)||r.next_race.toLocaleLowerCase("ja").includes(term))&&(state.race==="すべて"||r.next_race===state.race)&&(!state.newOnly||r.update==="NEW")).sort((a,b)=>{if(state.race==="すべて")return a.horse.localeCompare(b.horse,"ja");const ar=ranking.get(a.horse),br=ranking.get(b.horse);if(ar&&br)return br.total_yen-ar.total_yen||a.horse.localeCompare(b.horse,"ja");return(prize(b)?.yen??-1)-(prize(a)?.yen??-1)||a.horse.localeCompare(b.horse,"ja")})}
function render(){const detailed=state.race===state.special.race,ranking=ranked(),rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/pageSize));state.page=Math.min(state.page,pages);const shown=rows.slice((state.page-1)*pageSize,state.page*pageSize);e.count.textContent=rows.length;e.clear.hidden=!(state.query||state.race!=="すべて"||state.newOnly);e.sort.textContent=state.race==="すべて"?"馬名50音順":"出走順位の目安順";e.summary.hidden=!detailed;e.table.className=detailed?"rankingTable":"";e.third.textContent=detailed?state.special.full_gate:state.rows.filter(r=>r.update==="NEW").length;e.thirdLabel.textContent=detailed?"フルゲート":"NEW";e.source.href=detailed?state.special.source_url:state.data.source_url;
if(detailed){const c=state.special.rows[state.special.full_gate-1];e.raceTitle.innerHTML=`${esc(state.special.race)} <small>${esc(state.special.grade)}</small>`;e.raceMeta.textContent=`${state.special.race_date.replaceAll("-","/")}・${state.special.venue}・${state.special.distance}・${state.special.conditions}`;e.cutoff.textContent=`${c.horse}・${format(c.total_yen)}`;e.head.innerHTML='<tr><th>順位目安</th><th>馬名</th><th>想定騎手</th><th class="numeric">現在</th><th class="numeric">1年加算</th><th class="numeric">2年GI加算</th><th class="numeric totalHead">合計</th><th class="numeric">斤量</th><th>次走</th></tr>';e.body.innerHTML=shown.map(row=>{const d=ranking.get(row.horse);return`<tr class="${d.rank===state.special.full_gate?'cutoffRow':''}"><td><span class="rankBadge">${d.rank}</span></td><td>${link(row.horse_url,row.horse)}</td><td>${d.jockey?esc(d.jockey):'<span class="unverified">未定</span>'}</td><td class="numeric">${format(d.current_yen)}</td><td class="numeric plus">+${format(d.one_year_yen)}</td><td class="numeric plus">+${format(d.two_year_g1_yen)}</td><td class="numeric totalCell">${format(d.total_yen)}</td><td class="numeric">${d.weight_kg}kg<small class="estimate">目安</small></td><td>${link(state.special.source_url,state.special.race)}</td></tr>`}).join("");e.notice.textContent=`※${state.special.calculation_note} 斤量は別定条件から算出した暫定値です。`}else{e.head.innerHTML='<tr><th>更新</th><th>馬名</th><th class="numeric">収得賞金（平地）</th><th>予定レース</th></tr>';e.body.innerHTML=shown.map(row=>`<tr><td>${row.update==="NEW"?'<span class="newBadge">NEW</span>':""}</td><td>${link(row.horse_url,row.horse)}</td><td class="numeric">${prize(row)?format(prize(row).yen):'<span class="unverified">未取得</span>'}</td><td>${link(row.race_url,row.next_race)}</td></tr>`).join("");e.notice.textContent="※掲載情報は出走予定の段階です。取材後・公開後に変更される場合があります。"}if(!shown.length)e.body.innerHTML=`<tr><td class="empty" colspan="${detailed?9:4}">条件に一致する馬が見つかりません。</td></tr>`;e.pagination.hidden=pages<=1;e.prev.disabled=state.page===1;e.next.disabled=state.page===pages;e.pageNo.textContent=`${state.page} / ${pages}`}
async function load(){try{const v=`?v=${Date.now()}`;const[race,special,lab,jra]=await Promise.all([fetch(`./app/next-races.json${v}`),fetch(`./app/chukyo-kinen-2026.json${v}`),fetch(`./app/data-lab-prize-money.json${v}`),fetch(`./app/jra-prize-money.json${v}`)]);if(!race.ok||!special.ok||!lab.ok||!jra.ok)throw Error();state.data=await race.json();state.special=await special.json();state.jra=await jra.json();state.dataLab=new Map((await lab.json()).map(x=>[x.KettoNum,{yen:x.PrizeYen}]));composeRows();const races=[...new Set(state.rows.map(r=>r.next_race))].filter(Boolean).sort((a,b)=>a.localeCompare(b,"ja"));e.race.innerHTML='<option>すべて</option>'+races.map(r=>`<option>${esc(r)}</option>`).join("");e.updated.textContent=state.data.page_updated;e.horseCount.textContent=state.rows.length;e.raceCount.textContent=races.length;render()}catch{e.body.innerHTML='<tr><td class="empty">データを読み込めませんでした。</td></tr>'}}
e.query.addEventListener("input",x=>{state.query=x.target.value;state.page=1;render()});e.race.addEventListener("change",x=>{state.race=x.target.value;state.page=1;render()});e.newOnly.addEventListener("change",x=>{state.newOnly=x.target.checked;state.page=1;render()});e.clear.addEventListener("click",()=>{state.query="";state.race="すべて";state.newOnly=false;state.page=1;e.query.value="";e.race.value="すべて";e.newOnly.checked=false;render()});e.prev.addEventListener("click",()=>{state.page--;render()});e.next.addEventListener("click",()=>{state.page++;render()});load();
